-- Secret-free, append-only business audit facts for the MySQL control plane.
CREATE TABLE IF NOT EXISTS audit_event (
    tenant_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    event_id VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    schema_version INT NOT NULL,
    event_type VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    channel VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    user_id VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    session_id VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    agent_app_id VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    revision BIGINT NULL,
    model_profile_id VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    tool_name VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    decision VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    latency_ms BIGINT NULL,
    error_type VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    input_tokens BIGINT NULL,
    output_tokens BIGINT NULL,
    model_cost_minor BIGINT NULL,
    tool_cost_minor BIGINT NULL,
    currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
    budget_used_tokens BIGINT NULL,
    budget_used_minor BIGINT NULL,
    execution_result VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    provider VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    model VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    request_id VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    trace_id VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    correlation_id VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    actor_type VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    actor_id VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    reason VARCHAR(4000) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    previous_version BIGINT NULL,
    next_version BIGINT NULL,
    occurred_at DATETIME(6) NOT NULL,
    digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    PRIMARY KEY (tenant_id, event_id),
    KEY audit_event_timeline_idx (tenant_id, occurred_at, event_id),
    KEY audit_event_app_idx (tenant_id, agent_app_id, occurred_at),
    KEY audit_event_channel_idx (tenant_id, channel, occurred_at),
    KEY audit_event_model_profile_idx (tenant_id, model_profile_id, occurred_at),
    CONSTRAINT audit_event_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id),
    CONSTRAINT audit_event_schema_ck CHECK (schema_version = 1),
    CONSTRAINT audit_event_revision_ck CHECK (revision IS NULL OR revision >= 0),
    CONSTRAINT audit_event_latency_ck CHECK (latency_ms IS NULL OR latency_ms >= 0),
    CONSTRAINT audit_event_usage_ck CHECK ((input_tokens IS NULL OR input_tokens >= 0) AND (output_tokens IS NULL OR output_tokens >= 0) AND (model_cost_minor IS NULL OR model_cost_minor >= 0) AND (tool_cost_minor IS NULL OR tool_cost_minor >= 0) AND (budget_used_tokens IS NULL OR budget_used_tokens >= 0) AND (budget_used_minor IS NULL OR budget_used_minor >= 0)),
    CONSTRAINT audit_event_version_ck CHECK ((previous_version IS NULL AND next_version IS NULL) OR (previous_version IS NOT NULL AND next_version = previous_version + 1)),
    CONSTRAINT audit_event_type_ck CHECK (event_type IN ('control_plane.changed', 'execution.started', 'execution.completed', 'execution.failed', 'execution.canceled', 'execution.timed_out', 'execution.fallback', 'execution.canary_selected', 'tool.allowed', 'tool.denied', 'tool.approval_required', 'tool.executed', 'tool.reconciliation_required', 'im.authorization_allowed', 'im.authorization_denied', 'im.ingress_accepted', 'im.ingress_duplicate', 'im.delivery_sent', 'im.delivery_retry_scheduled', 'im.delivery_dead_lettered', 'im.delivery_reconciled', 'budget.rejected', 'content.redacted', 'audit_incomplete')),
    CONSTRAINT audit_event_decision_ck CHECK (decision IN ('', 'allow', 'deny', 'approval_required', 'accepted', 'duplicate', 'rejected')),
    CONSTRAINT audit_event_error_ck CHECK (error_type IN ('', 'canceled', 'timeout', 'invalid', 'unauthenticated', 'rate_limited', 'duplicate', 'unavailable', 'storage', 'model', 'tool', 'provider_error', 'budget', 'redacted', 'conflict')),
    CONSTRAINT audit_event_result_ck CHECK (execution_result IN ('', 'success', 'failure', 'canceled', 'timeout', 'rejected')),
    CONSTRAINT audit_event_currency_ck CHECK ((model_cost_minor IS NULL AND tool_cost_minor IS NULL AND budget_used_minor IS NULL) OR currency <> '')
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
