// Package knowledge provides the platform-owned management boundary around an
// upstream Knowledge VectorStore. The agent still consumes the upstream
// knowledge.Knowledge interface; this package only handles authenticated,
// tenant/app-scoped corpus administration.
package knowledge

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"sort"
	"strings"
	"sync"
	"time"
	"unicode"
	"unicode/utf8"

	"github.com/XnLemon/trpc-agent-service/trpcservice/internal/nilvalue"
	"github.com/google/uuid"
	"trpc.group/trpc-go/trpc-agent-go/knowledge/document"
	"trpc.group/trpc-go/trpc-agent-go/knowledge/embedder"
	"trpc.group/trpc-go/trpc-agent-go/knowledge/vectorstore"
)

const (
	// AppMetadataKey is the reserved metadata key used by the runtime app
	// scope wrapper. Callers cannot change it to another app.
	AppMetadataKey = "_trpc_app_id"
	// PublishedMetadataKey identifies documents included in a published
	// corpus. It is reserved for future runtime publication filtering.
	PublishedMetadataKey = "_trpc_published"
	// VersionMetadataKey records the corpus version that last published a
	// document. It is informational until a provider supports version pinning.
	VersionMetadataKey = "_trpc_knowledge_version"

	maxDocumentIDRunes = 512
	maxScopeIDRunes    = 256
	maxNameRunes       = 2048
	maxContentRunes    = 4 << 20
	maxImportDocuments = 100
)

var (
	// ErrInvalid reports a malformed management request.
	ErrInvalid = errors.New("invalid knowledge management request")
	// ErrNotFound reports a document or version outside the requested scope.
	ErrNotFound = errors.New("knowledge management resource not found")
	// ErrConflict reports a concurrent or duplicate corpus mutation.
	ErrConflict = errors.New("knowledge management conflict")
	// ErrUnavailable reports a missing provider or embedder.
	ErrUnavailable = errors.New("knowledge management is unavailable")
	// ErrScope reports an app/tenant scope violation.
	ErrScope = errors.New("knowledge management scope violation")
)

// Scope is the only corpus lookup identity accepted by the management service.
// Tenant and app IDs are never inferred from document metadata or URL-like
// provider values.
type Scope struct {
	TenantID string
	AppID    string
}

func (scope Scope) Validate() error {
	if !validScopeID(scope.TenantID) || !validScopeID(scope.AppID) {
		return ErrScope
	}
	return nil
}

// Backend is one short-lived, already tenant/app-authorized provider handle.
// The manager calls Close, when supplied, after each operation. A provider
// that returns a shared handle must leave Close nil.
type Backend struct {
	Store    vectorstore.VectorStore
	Embedder embedder.Embedder
	Close    func() error
}

// Provider opens a corpus backend for exactly one scope. Implementations must
// perform their own tenant binding before returning a handle.
type Provider interface {
	Open(context.Context, Scope) (Backend, error)
}

// ProviderFunc adapts a function into a Provider.
type ProviderFunc func(context.Context, Scope) (Backend, error)

func (provider ProviderFunc) Open(ctx context.Context, scope Scope) (Backend, error) {
	if provider == nil || nilvalue.Is(ctx) {
		return Backend{}, ErrUnavailable
	}
	return provider(ctx, scope)
}

// DocumentInput is a server-side corpus mutation. Embeddings are generated by
// the configured embedder and are never accepted from the admin caller.
type DocumentInput struct {
	ID            string         `json:"id,omitempty"`
	Name          string         `json:"name,omitempty"`
	Content       string         `json:"content"`
	EmbeddingText string         `json:"embedding_text,omitempty"`
	Metadata      map[string]any `json:"metadata,omitempty"`
}

// UpdateInput uses pointers so PATCH can distinguish omitted fields from an
// explicit empty value. Metadata nil retains the existing metadata; a non-nil
// empty map clears user metadata.
type UpdateInput struct {
	Name          *string        `json:"name,omitempty"`
	Content       *string        `json:"content,omitempty"`
	EmbeddingText *string        `json:"embedding_text,omitempty"`
	Metadata      map[string]any `json:"metadata,omitempty"`
}

// Document is the safe management representation. It intentionally excludes
// the provider embedding vector.
type Document struct {
	TenantID      string         `json:"tenant_id"`
	AppID         string         `json:"app_id"`
	ID            string         `json:"id"`
	Name          string         `json:"name,omitempty"`
	Content       string         `json:"content"`
	EmbeddingText string         `json:"embedding_text,omitempty"`
	Metadata      map[string]any `json:"metadata,omitempty"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

// ListResult is a stable, ID-ordered page of documents.
type ListResult struct {
	Items      []Document `json:"items"`
	NextCursor string     `json:"next_cursor,omitempty"`
}

// ImportInput imports bounded text documents in one request. The operation is
// idempotent for an explicit document ID and replaces that document's content.
type ImportInput struct {
	Documents []DocumentInput `json:"documents"`
}

// ImportResult reports every successfully imported document without exposing
// vectors or provider implementation details.
type ImportResult struct {
	TenantID string     `json:"tenant_id"`
	AppID    string     `json:"app_id"`
	Items    []Document `json:"items"`
	Count    int        `json:"count"`
}

// RebuildResult reports a completed embedding rebuild. A failed operation is
// returned as an error and never claims success for documents not processed.
type RebuildResult struct {
	TenantID string `json:"tenant_id"`
	AppID    string `json:"app_id"`
	Count    int    `json:"count"`
}

// Version is a published corpus manifest. The manifest contains a digest of
// document content and metadata, not embedding values or source credentials.
type Version struct {
	TenantID      string    `json:"tenant_id"`
	AppID         string    `json:"app_id"`
	Version       int64     `json:"version"`
	DocumentCount int       `json:"document_count"`
	ContentDigest string    `json:"content_digest"`
	ActorID       string    `json:"actor_id"`
	PublishedAt   time.Time `json:"published_at"`
}

// VersionStore persists corpus publication manifests. It is separate from the
// VectorStore because upstream has no version/publication contract.
type VersionStore interface {
	PublishVersion(context.Context, Version) (Version, error)
	ListVersions(context.Context, Scope) ([]Version, error)
}

// Service is consumed by the authenticated Admin handler.
type Service interface {
	ListDocuments(context.Context, Scope, string, int) (ListResult, error)
	GetDocument(context.Context, Scope, string) (Document, error)
	CreateDocument(context.Context, Scope, DocumentInput) (Document, error)
	UpdateDocument(context.Context, Scope, string, UpdateInput) (Document, error)
	ImportDocuments(context.Context, Scope, ImportInput) (ImportResult, error)
	DeleteDocument(context.Context, Scope, string) error
	Rebuild(context.Context, Scope) (RebuildResult, error)
	Publish(context.Context, Scope, string) (Version, error)
	ListVersions(context.Context, Scope) ([]Version, error)
}

// Manager implements Service using upstream VectorStore and Embedder
// contracts. It has no process-global tenant or app state.
type Manager struct {
	provider Provider
	versions VersionStore
}

// NewManager creates a management service. If no VersionStore is supplied,
// publication manifests are held in a concurrency-safe in-memory store; a
// production deployment should inject its durable implementation.
func NewManager(provider Provider, versions VersionStore) (*Manager, error) {
	if nilvalue.Is(provider) {
		return nil, ErrUnavailable
	}
	if nilvalue.Is(versions) {
		versions = newMemoryVersionStore()
	}
	return &Manager{provider: provider, versions: versions}, nil
}

func (manager *Manager) ListDocuments(ctx context.Context, scope Scope, cursor string, limit int) (ListResult, error) {
	if err := check(ctx, scope); err != nil {
		return ListResult{}, err
	}
	if limit <= 0 {
		limit = 50
	}
	if limit > 200 {
		limit = 200
	}
	offset, err := parseCursor(cursor)
	if err != nil {
		return ListResult{}, err
	}
	backend, err := manager.open(ctx, scope)
	if err != nil {
		return ListResult{}, err
	}
	defer manager.close(backend)
	metadata, err := backend.Store.GetMetadata(ctx)
	if err != nil {
		return ListResult{}, mapProviderError(err)
	}
	ids := make([]string, 0, len(metadata))
	for id, value := range metadata {
		if appMetadata(value.Metadata) == scope.AppID {
			ids = append(ids, id)
		}
	}
	sort.Strings(ids)
	if offset > len(ids) {
		offset = len(ids)
	}
	end := offset + limit
	if end > len(ids) {
		end = len(ids)
	}
	items := make([]Document, 0, end-offset)
	for _, id := range ids[offset:end] {
		value, _, getErr := backend.Store.Get(ctx, id)
		if getErr != nil {
			return ListResult{}, mapProviderError(getErr)
		}
		if value == nil || value.ID != id || !belongs(value, scope) {
			// GetMetadata is only a candidate index. A provider that changes or
			// loses the reserved proof between the index read and Get must not
			// silently turn an unproven row into a successful page.
			return ListResult{}, ErrScope
		}
		items = append(items, toDocument(scope, value))
	}
	result := ListResult{Items: items}
	if end < len(ids) {
		result.NextCursor = fmt.Sprintf("%d", end)
	}
	return result, nil
}

func (manager *Manager) GetDocument(ctx context.Context, scope Scope, id string) (Document, error) {
	if err := check(ctx, scope); err != nil {
		return Document{}, err
	}
	if !validDocumentID(id) {
		return Document{}, ErrInvalid
	}
	backend, err := manager.open(ctx, scope)
	if err != nil {
		return Document{}, err
	}
	defer manager.close(backend)
	value, _, err := backend.Store.Get(ctx, id)
	if err != nil {
		return Document{}, mapProviderError(err)
	}
	if value == nil || value.ID != id || !belongs(value, scope) {
		return Document{}, ErrNotFound
	}
	return toDocument(scope, value), nil
}

func (manager *Manager) CreateDocument(ctx context.Context, scope Scope, input DocumentInput) (Document, error) {
	if err := check(ctx, scope); err != nil {
		return Document{}, err
	}
	value, err := normalizeInput(scope, input, false)
	if err != nil {
		return Document{}, err
	}
	if value.ID == "" {
		value.ID = "doc_" + uuid.NewString()
	}
	backend, err := manager.open(ctx, scope)
	if err != nil {
		return Document{}, err
	}
	defer manager.close(backend)
	if existing, _, getErr := backend.Store.Get(ctx, value.ID); getErr == nil {
		if existing == nil || existing.ID != value.ID || !belongs(existing, scope) {
			return Document{}, ErrScope
		}
		return Document{}, ErrConflict
	} else if !isProviderNotFound(getErr) {
		return Document{}, mapProviderError(getErr)
	}
	return manager.write(ctx, scope, backend, value, false)
}

func (manager *Manager) UpdateDocument(ctx context.Context, scope Scope, id string, input UpdateInput) (Document, error) {
	if err := check(ctx, scope); err != nil {
		return Document{}, err
	}
	if !validDocumentID(id) {
		return Document{}, ErrInvalid
	}
	backend, err := manager.open(ctx, scope)
	if err != nil {
		return Document{}, err
	}
	defer manager.close(backend)
	current, embedding, err := backend.Store.Get(ctx, id)
	if err != nil {
		return Document{}, mapProviderError(err)
	}
	if current == nil || current.ID != id || !belongs(current, scope) {
		return Document{}, ErrNotFound
	}
	candidate := DocumentInput{ID: id, Name: current.Name, Content: current.Content, EmbeddingText: current.EmbeddingText, Metadata: cloneMetadata(current.Metadata)}
	if input.Name != nil {
		candidate.Name = *input.Name
	}
	if input.Content != nil {
		candidate.Content = *input.Content
	}
	if input.EmbeddingText != nil {
		candidate.EmbeddingText = *input.EmbeddingText
	}
	if input.Metadata != nil {
		candidate.Metadata = cloneMetadata(input.Metadata)
	}
	value, err := normalizeInput(scope, candidate, true)
	if err != nil {
		return Document{}, err
	}
	// Reuse the stored embedding only when the embedding text did not change.
	// This avoids an unnecessary remote call while still rebuilding correctly
	// for content or explicit embedding-text changes.
	if value.EmbeddingText == current.EmbeddingText && value.Content == current.Content && value.Name == current.Name && metadataEqual(value.Metadata, current.Metadata) {
		return toDocument(scope, current), nil
	}
	if value.EmbeddingText == current.EmbeddingText && value.Content == current.Content {
		return manager.writeWithEmbedding(ctx, scope, backend, value, embedding, true)
	}
	return manager.write(ctx, scope, backend, value, true)
}

func (manager *Manager) ImportDocuments(ctx context.Context, scope Scope, input ImportInput) (ImportResult, error) {
	if err := check(ctx, scope); err != nil {
		return ImportResult{}, err
	}
	if len(input.Documents) == 0 || len(input.Documents) > maxImportDocuments {
		return ImportResult{}, ErrInvalid
	}
	// Normalize the complete batch before opening or mutating the provider. In
	// particular, a malformed later item must not leave an earlier item
	// partially imported. Explicit duplicate IDs are rejected rather than
	// making the result depend on input order.
	normalized := make([]DocumentInput, 0, len(input.Documents))
	seen := make(map[string]struct{}, len(input.Documents))
	for _, raw := range input.Documents {
		value, normalizeErr := normalizeInput(scope, raw, false)
		if normalizeErr != nil {
			return ImportResult{}, normalizeErr
		}
		if value.ID == "" {
			value.ID = "doc_" + uuid.NewString()
		}
		if _, exists := seen[value.ID]; exists {
			return ImportResult{}, ErrConflict
		}
		seen[value.ID] = struct{}{}
		normalized = append(normalized, value)
	}
	backend, err := manager.open(ctx, scope)
	if err != nil {
		return ImportResult{}, err
	}
	defer manager.close(backend)
	items := make([]Document, 0, len(normalized))
	for _, value := range normalized {
		replace := false
		if existing, _, getErr := backend.Store.Get(ctx, value.ID); getErr == nil {
			if existing == nil || existing.ID != value.ID || !belongs(existing, scope) {
				return ImportResult{}, ErrScope
			}
			replace = true
		} else if !isProviderNotFound(getErr) {
			return ImportResult{}, mapProviderError(getErr)
		}
		if written, writeErr := manager.write(ctx, scope, backend, value, replace); writeErr != nil {
			return ImportResult{}, writeErr
		} else {
			items = append(items, written)
		}
	}
	return ImportResult{TenantID: scope.TenantID, AppID: scope.AppID, Items: items, Count: len(items)}, nil
}

func (manager *Manager) DeleteDocument(ctx context.Context, scope Scope, id string) error {
	if err := check(ctx, scope); err != nil {
		return err
	}
	if !validDocumentID(id) {
		return ErrInvalid
	}
	backend, err := manager.open(ctx, scope)
	if err != nil {
		return err
	}
	defer manager.close(backend)
	value, _, err := backend.Store.Get(ctx, id)
	if err != nil {
		return mapProviderError(err)
	}
	if value == nil || value.ID != id || !belongs(value, scope) {
		return ErrNotFound
	}
	if err := backend.Store.Delete(ctx, id); err != nil {
		return mapProviderError(err)
	}
	return nil
}

func (manager *Manager) Rebuild(ctx context.Context, scope Scope) (RebuildResult, error) {
	if err := check(ctx, scope); err != nil {
		return RebuildResult{}, err
	}
	backend, err := manager.open(ctx, scope)
	if err != nil {
		return RebuildResult{}, err
	}
	defer manager.close(backend)
	metadata, err := backend.Store.GetMetadata(ctx)
	if err != nil {
		return RebuildResult{}, mapProviderError(err)
	}
	ids := make([]string, 0, len(metadata))
	for id, value := range metadata {
		if appMetadata(value.Metadata) == scope.AppID {
			ids = append(ids, id)
		}
	}
	sort.Strings(ids)
	processed := 0
	for _, id := range ids {
		value, _, getErr := backend.Store.Get(ctx, id)
		if getErr != nil {
			return RebuildResult{}, mapProviderError(getErr)
		}
		if value == nil || value.ID != id || !belongs(value, scope) {
			return RebuildResult{}, ErrScope
		}
		text := value.EmbeddingText
		if text == "" {
			text = value.Content
		}
		embedding, embedErr := manager.embed(ctx, backend, text)
		if embedErr != nil {
			return RebuildResult{}, embedErr
		}
		if err := backend.Store.Update(ctx, value, embedding); err != nil {
			return RebuildResult{}, mapProviderError(err)
		}
		processed++
	}
	return RebuildResult{TenantID: scope.TenantID, AppID: scope.AppID, Count: processed}, nil
}

func (manager *Manager) Publish(ctx context.Context, scope Scope, actorID string) (Version, error) {
	if err := check(ctx, scope); err != nil {
		return Version{}, err
	}
	if actorID != strings.TrimSpace(actorID) {
		return Version{}, ErrInvalid
	}
	actorID = strings.TrimSpace(actorID)
	if actorID == "" || !validText(actorID, 256, true) {
		return Version{}, ErrInvalid
	}
	result, err := manager.ListDocuments(ctx, scope, "", maxImportDocuments)
	if err != nil {
		return Version{}, err
	}
	if result.NextCursor != "" {
		// Published manifests must represent the complete corpus. Fetch the
		// remaining pages rather than silently publishing a truncated digest.
		cursor := result.NextCursor
		for cursor != "" {
			next, listErr := manager.ListDocuments(ctx, scope, cursor, maxImportDocuments)
			if listErr != nil {
				return Version{}, listErr
			}
			result.Items = append(result.Items, next.Items...)
			cursor = next.NextCursor
		}
	}
	digest, err := digestDocuments(result.Items)
	if err != nil {
		return Version{}, err
	}
	return callPublishVersion(manager.versions, ctx, Version{TenantID: scope.TenantID, AppID: scope.AppID, DocumentCount: len(result.Items), ContentDigest: digest, ActorID: actorID, PublishedAt: time.Now().UTC()})
}

func (manager *Manager) ListVersions(ctx context.Context, scope Scope) ([]Version, error) {
	if err := check(ctx, scope); err != nil {
		return nil, err
	}
	values, err := callListVersions(manager.versions, ctx, scope)
	if err != nil {
		return nil, mapProviderError(err)
	}
	if values == nil {
		values = make([]Version, 0)
	}
	for index := range values {
		if values[index].TenantID != scope.TenantID || values[index].AppID != scope.AppID {
			return nil, ErrScope
		}
		if !validVersionRecord(values[index]) {
			return nil, ErrUnavailable
		}
	}
	return values, nil
}

func (manager *Manager) open(ctx context.Context, scope Scope) (Backend, error) {
	if manager == nil || nilvalue.Is(manager.provider) || nilvalue.Is(ctx) {
		return Backend{}, ErrUnavailable
	}
	backend, err := callProviderOpen(manager.provider, ctx, scope)
	if err != nil {
		return Backend{}, mapProviderError(err)
	}
	if nilvalue.Is(backend.Store) || nilvalue.Is(backend.Embedder) {
		if backend.Close != nil {
			_ = callBackendClose(backend.Close)
		}
		return Backend{}, ErrUnavailable
	}
	return backend, nil
}

func (manager *Manager) close(backend Backend) {
	if backend.Close != nil {
		_ = callBackendClose(backend.Close)
	}
}

func (manager *Manager) write(ctx context.Context, scope Scope, backend Backend, input DocumentInput, replace bool) (Document, error) {
	embeddingText := input.EmbeddingText
	if embeddingText == "" {
		embeddingText = input.Content
	}
	embedding, err := manager.embed(ctx, backend, embeddingText)
	if err != nil {
		return Document{}, err
	}
	return manager.writeWithEmbedding(ctx, scope, backend, input, embedding, replace)
}

func (manager *Manager) writeWithEmbedding(ctx context.Context, scope Scope, backend Backend, input DocumentInput, embedding []float64, replace bool) (Document, error) {
	value := &document.Document{ID: input.ID, Name: input.Name, Content: input.Content, EmbeddingText: input.EmbeddingText, Metadata: cloneMetadata(input.Metadata)}
	var writeErr error
	if replace {
		writeErr = backend.Store.Update(ctx, value, embedding)
	} else {
		writeErr = backend.Store.Add(ctx, value, embedding)
	}
	if writeErr != nil {
		return Document{}, mapProviderError(writeErr)
	}
	stored, _, err := backend.Store.Get(ctx, input.ID)
	if err != nil {
		return Document{}, mapProviderError(err)
	}
	if stored == nil || stored.ID != input.ID || !belongs(stored, scope) {
		return Document{}, ErrScope
	}
	return toDocument(scope, stored), nil
}

func (manager *Manager) embed(ctx context.Context, backend Backend, text string) ([]float64, error) {
	if nilvalue.Is(ctx) || nilvalue.Is(backend.Embedder) || strings.TrimSpace(text) == "" {
		return nil, ErrInvalid
	}
	values, err := callEmbedder(backend.Embedder, ctx, text)
	if err != nil {
		return nil, ErrUnavailable
	}
	if len(values) == 0 || !finite(values) {
		return nil, ErrInvalid
	}
	return values, nil
}

func check(ctx context.Context, scope Scope) error {
	if nilvalue.Is(ctx) {
		return ErrInvalid
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	return scope.Validate()
}

func normalizeInput(scope Scope, input DocumentInput, update bool) (DocumentInput, error) {
	if err := scope.Validate(); err != nil {
		return DocumentInput{}, err
	}
	if input.ID != strings.TrimSpace(input.ID) {
		return DocumentInput{}, ErrInvalid
	}
	input.ID = strings.TrimSpace(input.ID)
	input.Name = strings.TrimSpace(input.Name)
	input.EmbeddingText = strings.TrimSpace(input.EmbeddingText)
	if input.ID != "" && !validDocumentID(input.ID) {
		return DocumentInput{}, ErrInvalid
	}
	if update && input.ID == "" {
		return DocumentInput{}, ErrInvalid
	}
	if !validText(input.Name, maxNameRunes, false) || !validText(input.Content, maxContentRunes, true) || !validText(input.EmbeddingText, maxContentRunes, false) {
		return DocumentInput{}, ErrInvalid
	}
	metadata := cloneMetadata(input.Metadata)
	if metadata == nil {
		metadata = make(map[string]any)
	}
	if value, exists := metadata[AppMetadataKey]; exists && value != scope.AppID {
		return DocumentInput{}, ErrScope
	}
	metadata[AppMetadataKey] = scope.AppID
	metadata[PublishedMetadataKey] = false
	delete(metadata, VersionMetadataKey)
	if _, err := json.Marshal(metadata); err != nil {
		return DocumentInput{}, ErrInvalid
	}
	input.Metadata = metadata
	return input, nil
}

func validScopeID(value string) bool {
	return value == strings.TrimSpace(value) && validText(value, maxScopeIDRunes, true) && !strings.Contains(value, "://")
}

func validDocumentID(value string) bool {
	return value == strings.TrimSpace(value) && validText(value, maxDocumentIDRunes, true) && !strings.Contains(value, "://")
}

func validText(value string, max int, required bool) bool {
	if !utf8.ValidString(value) {
		return false
	}
	if required && strings.TrimSpace(value) == "" {
		return false
	}
	if !required && strings.TrimSpace(value) == "" {
		return value == ""
	}
	if len([]rune(value)) > max {
		return false
	}
	for _, character := range value {
		if unicode.IsControl(character) {
			return false
		}
	}
	return true
}

func finite(values []float64) bool {
	for _, value := range values {
		if math.IsNaN(value) || math.IsInf(value, 0) {
			return false
		}
	}
	return true
}

func appMetadata(metadata map[string]any) string {
	value, _ := metadata[AppMetadataKey].(string)
	return value
}

func belongs(value *document.Document, scope Scope) bool {
	return value != nil && validDocumentID(value.ID) && appMetadata(value.Metadata) == scope.AppID
}

func toDocument(scope Scope, value *document.Document) Document {
	return Document{TenantID: scope.TenantID, AppID: scope.AppID, ID: value.ID, Name: value.Name, Content: value.Content, EmbeddingText: value.EmbeddingText, Metadata: cloneMetadata(value.Metadata), CreatedAt: value.CreatedAt, UpdatedAt: value.UpdatedAt}
}

func cloneMetadata(metadata map[string]any) map[string]any {
	if metadata == nil {
		return nil
	}
	copy := make(map[string]any, len(metadata))
	for key, value := range metadata {
		copy[key] = value
	}
	return copy
}

func metadataEqual(left, right map[string]any) bool {
	leftJSON, leftErr := json.Marshal(left)
	rightJSON, rightErr := json.Marshal(right)
	return leftErr == nil && rightErr == nil && string(leftJSON) == string(rightJSON)
}

func validVersionRecord(value Version) bool {
	if !validScopeID(value.TenantID) || !validScopeID(value.AppID) || value.Version < 1 || value.DocumentCount < 0 || len(value.ContentDigest) != sha256.Size*2 || strings.ToLower(value.ContentDigest) != value.ContentDigest || value.PublishedAt.IsZero() || value.PublishedAt.Location() != time.UTC || value.ActorID != strings.TrimSpace(value.ActorID) || !validText(value.ActorID, 256, true) {
		return false
	}
	_, err := hex.DecodeString(value.ContentDigest)
	return err == nil
}

func digestDocuments(values []Document) (string, error) {
	copy := append([]Document(nil), values...)
	sort.Slice(copy, func(i, j int) bool { return copy[i].ID < copy[j].ID })
	for index := range copy {
		copy[index].TenantID = ""
		copy[index].AppID = ""
		copy[index].CreatedAt = time.Time{}
		copy[index].UpdatedAt = time.Time{}
	}
	encoded, err := json.Marshal(copy)
	if err != nil {
		return "", ErrInvalid
	}
	sum := sha256.Sum256(encoded)
	return hex.EncodeToString(sum[:]), nil
}

func parseCursor(cursor string) (int, error) {
	cursor = strings.TrimSpace(cursor)
	if cursor == "" {
		return 0, nil
	}
	var offset int
	if _, err := fmt.Sscanf(cursor, "%d", &offset); err != nil || offset < 0 || fmt.Sprintf("%d", offset) != cursor {
		return 0, ErrInvalid
	}
	return offset, nil
}

func isProviderNotFound(err error) bool {
	return !nilvalue.Is(err) && (errors.Is(err, ErrNotFound) || strings.Contains(strings.ToLower(err.Error()), "not found"))
}

func callPublishVersion(store VersionStore, ctx context.Context, value Version) (published Version, err error) {
	if nilvalue.Is(store) || nilvalue.Is(ctx) {
		return Version{}, ErrUnavailable
	}
	defer func() {
		if recover() != nil {
			published, err = Version{}, ErrUnavailable
		}
	}()
	return store.PublishVersion(ctx, value)
}

func callListVersions(store VersionStore, ctx context.Context, scope Scope) (values []Version, err error) {
	if nilvalue.Is(store) || nilvalue.Is(ctx) {
		return nil, ErrUnavailable
	}
	defer func() {
		if recover() != nil {
			values, err = nil, ErrUnavailable
		}
	}()
	return store.ListVersions(ctx, scope)
}

func callProviderOpen(provider Provider, ctx context.Context, scope Scope) (backend Backend, err error) {
	if nilvalue.Is(provider) || nilvalue.Is(ctx) {
		return Backend{}, ErrUnavailable
	}
	defer func() {
		if recover() != nil {
			backend, err = Backend{}, ErrUnavailable
		}
	}()
	return provider.Open(ctx, scope)
}

func callEmbedder(embedderValue embedder.Embedder, ctx context.Context, text string) (values []float64, err error) {
	if nilvalue.Is(embedderValue) || nilvalue.Is(ctx) {
		return nil, ErrUnavailable
	}
	defer func() {
		if recover() != nil {
			values, err = nil, ErrUnavailable
		}
	}()
	return embedderValue.GetEmbedding(ctx, text)
}

func callBackendClose(closeFunc func() error) (err error) {
	if closeFunc == nil {
		return nil
	}
	defer func() {
		if recover() != nil {
			err = ErrUnavailable
		}
	}()
	return closeFunc()
}

func mapProviderError(err error) error {
	if nilvalue.Is(err) {
		return nil
	}
	if errors.Is(err, ErrInvalid) || errors.Is(err, ErrNotFound) || errors.Is(err, ErrConflict) || errors.Is(err, ErrUnavailable) || errors.Is(err, ErrScope) {
		return err
	}
	if isProviderNotFound(err) {
		return ErrNotFound
	}
	return ErrUnavailable
}

type memoryVersionStore struct {
	mu     sync.Mutex
	values map[string][]Version
}

func newMemoryVersionStore() *memoryVersionStore {
	return &memoryVersionStore{values: make(map[string][]Version)}
}

func (store *memoryVersionStore) PublishVersion(ctx context.Context, value Version) (Version, error) {
	if err := validateVersionInput(ctx, value); err != nil {
		return Version{}, err
	}
	store.mu.Lock()
	defer store.mu.Unlock()
	key := value.TenantID + "\x00" + value.AppID
	values := store.values[key]
	for _, existing := range values {
		if existing.ContentDigest == value.ContentDigest {
			return existing, nil
		}
	}
	value.Version = int64(len(values) + 1)
	store.values[key] = append(values, value)
	return value, nil
}

func (store *memoryVersionStore) ListVersions(ctx context.Context, scope Scope) ([]Version, error) {
	if nilvalue.Is(ctx) {
		return nil, ErrInvalid
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if err := scope.Validate(); err != nil {
		return nil, err
	}
	store.mu.Lock()
	defer store.mu.Unlock()
	values := append([]Version(nil), store.values[scope.TenantID+"\x00"+scope.AppID]...)
	for left, right := 0, len(values)-1; left < right; left, right = left+1, right-1 {
		values[left], values[right] = values[right], values[left]
	}
	return values, nil
}

func validateVersionInput(ctx context.Context, value Version) error {
	if nilvalue.Is(ctx) {
		return ErrInvalid
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	if !validScopeID(value.TenantID) || !validScopeID(value.AppID) || value.Version != 0 || value.DocumentCount < 0 || len(value.ContentDigest) != sha256.Size*2 || strings.ToLower(value.ContentDigest) != value.ContentDigest || value.PublishedAt.IsZero() || value.PublishedAt.Location() != time.UTC || value.ActorID != strings.TrimSpace(value.ActorID) || !validText(value.ActorID, 256, true) {
		return ErrInvalid
	}
	if _, err := hex.DecodeString(value.ContentDigest); err != nil {
		return ErrInvalid
	}
	return nil
}

var _ Service = (*Manager)(nil)
var _ VersionStore = (*memoryVersionStore)(nil)
